services:
  # PostgreSQL Database
  postgres:
    image: postgres:latest
    container_name: cilliarp-postgres
    restart: always
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    volumes:
      - cilliarp_postgres_data:/var/lib/postgresql/data
    networks:
      - cilliarp-network

  # MinIO Object Storage
  minio:
    image: minio/minio
    container_name: cilliarp-minio
    restart: always
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "${MINIO_PORT}:${MINIO_PORT}"
      - "${MINIO_CONSOLE_PORT}:${MINIO_CONSOLE_PORT}"
    volumes:
      - cilliarp_minio_data:/data
    networks:
      - cilliarp-network

  # NestJS Application (opcional - para desenvolvimento)
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cilliarp-api
    restart: always
    environment:
      - NODE_ENV=${NODE_ENV}
      - DATABASE_URL=${DATABASE_URL}
      - MINIO_ENDPOINT=${MINIO_ENDPOINT}
      - MINIO_PORT=${MINIO_PORT}
      - MINIO_ACCESS_KEY=${MINIO_ROOT_USER}
      - MINIO_SECRET_KEY=${MINIO_ROOT_PASSWORD}
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - postgres
      - minio
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - cilliarp-network
    profiles:
      - full

volumes:
  cilliarp_postgres_data:
    driver: local
  cilliarp_minio_data:
    driver: local

networks:
  cilliarp-network:
    driver: bridge
